name: Makefile CI

on:
  workflow_dispatch:
    inputs: 
      tag:
        description: 'Release tag (eg v1.2.3)'
        required: true
      release_name:
        description: 'Release name'
        required: true

permissions:
  contents: write
  
jobs:
  build-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make build
      run: make build
      
    - name: Create git tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ github.event.inputs.tag }}
        git push origin ${{ github.event.inputs.tag }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.release_name }}
        files: |
          ./build.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
